spring:
  rabbitmq:
    host: 192.168.3.157
    username: admin
    password: admin
    virtual-host: /
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 13000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh